name: Deploy Infrastructure

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "Terraform CI/CD"
    runs-on: ubuntu-latest
    env:
      TF_VAR_oidc_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    outputs:
      storage_account_name: ${{ steps.tf-outputs.outputs.storage_account_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform -chdir=infra init

      - name: Terraform Validate
        run: terraform -chdir=infra validate

      - name: Terraform Plan
        run: terraform -chdir=infra plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=infra apply -auto-approve

      - name: Terraform Output
        id: tf-outputs
        run: |
          echo "storage_account_name=$(terraform -chdir=infra output -raw storage_account_name)" >> $GITHUB_OUTPUT

  web:
    name: "Web Page CI/CD"
    runs-on: ubuntu-latest
    needs: terraform
    env:
      TF_VAR_oidc_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload static site to Azure Storage
        uses: azure/cli@v2
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ needs.terraform.outputs.storage_account_name }} \
              --destination '$web' \
              --source app/web \
              --overwrite \
              --auth-mode login


