name: Deploy Infrastructure

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:

permissions:
  id-token: write
  contents: read

env:
  TF_VAR_oidc_client_id: ${{ secrets.AZURE_CLIENT_ID }}
  TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
  TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  DEPLOY_ENV: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}

jobs:
  terraform:
    name: "Terraform CI/CD"
    runs-on: ubuntu-latest
    environment: ${{ github.DEPLOY_ENV }}

    outputs:
      storage_account_name: ${{ steps.tf-outputs.outputs.storage_account_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform -chdir=infra init \
          -backend-config="key=terraform-${{  env.DEPLOY_ENV  }}.tfstate"

      - name: Terraform Validate
        run: terraform -chdir=infra validate

      - name: Terraform Plan
        id: plan
        run: terraform -chdir=infra plan -no-color > plan.txt
      
      - name: Comment PR with Terraform Plan
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('infra/plan.txt', 'utf8');

            const body = `
            ## Terraform Plan

            <details>
            <summary>Click to expand</summary>

            \`\`\`
            ${plan}
            \`\`\`

            </details>
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: |
          terraform -chdir=infra apply \
            -var="environment=${{  env.DEPLOY_ENV  }}" \
            -auto-approve

      - name: Terraform Output
        id: tf-outputs
        run: |
          echo "storage_account_name=$(terraform -chdir=infra output -raw storage_account_name)" >> $GITHUB_OUTPUT
          echo "function_app_url=$(terraform -chdir=infra output -raw function_app_url)" >> $GITHUB_OUTPUT

  web:
    name: "Web Page CI/CD"
    runs-on: ubuntu-latest
    needs: terraform
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Inject API URL into frontend
        run: |
          sed -i "s|__API_BASE_URL__|https://${{ needs.terraform.outputs.function_app_url }}|g" app/web/script.js

      - name: Upload static site to Azure Storage
        uses: azure/cli@v2
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ needs.terraform.outputs.storage_account_name }} \
              --destination '$web' \
              --source app/web \
              --overwrite \
              --auth-mode login

  api:
    name: "API CI/CD"
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd app/api
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: cloudportfolio-${{  github.environment  }}-fn
          package: app/api
